name: image-proxy

services:
  api:
    container_name: image-proxy
    build:
      context: '.'
      dockerfile: Dockerfile
    env_file:
      - path: ./.env.docker
        required: true
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.services.img_proxy_api.loadbalancer.server.port=${APP_PORT}
      - traefik.http.routers.img_proxy_api.rule=Host(`${APP_DOMAIN}`) && PathPrefix(`/${APP_PATH_PREFIX}/`)
      - traefik.http.routers.img_proxy_api.entrypoints=websecure
      - traefik.http.routers.img_proxy_api.service=img_proxy_api
      - traefik.http.routers.img_proxy_api.tls=true
      - traefik.http.routers.img_proxy_api.tls.certresolver=${CERT_RESOLVER}
      - traefik.http.routers.img_proxy_api.middlewares=img_proxy_strip@docker
      - traefik.http.middlewares.img_proxy_strip.stripprefix.prefixes=/image
    ports:
      - ${APP_PORT}:${APP_PORT}
    networks:
      - proxy_net

networks:
  proxy_net:
    name: proxy_net
    external: true
